// Opt-in: real backend and paid LLM calls. Never accepts/redeems an offer.
import {chromium} from '../frontend/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import {mkdirSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
if(process.env.OFFERMESH_LIVE_UI_TEST!=='1')throw new Error('Set OFFERMESH_LIVE_UI_TEST=1 to authorize paid localhost testing.');
const base='http://127.0.0.1:5173';
const out=new URL('../frontend/test-results/clarification/',import.meta.url);mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true,channel:'msedge'});
const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(20000);
const shot=async name=>{await page.waitForTimeout(400);await page.screenshot({path:fileURLToPath(new URL(name+'.png',out)),fullPage:true});};
try {
  await page.goto(base+'/chat');
  await page.getByRole('textbox',{name:'輸入購物需求'}).waitFor();await shot('01-home');
  await page.getByRole('button',{name:'開啟設定',exact:true}).click();
  await page.getByRole('button',{name:'進階文字偏好設定',exact:true}).click();
  await page.getByRole('tab',{name:/preference.md/}).click();
  await page.getByRole('textbox',{name:'編輯 preference.md'}).fill('偏好黑色');
  await page.getByRole('button',{name:'儲存設定',exact:true}).click();
  await page.getByRole('button',{name:'返回對話',exact:true}).click();
  await page.getByRole('textbox',{name:'輸入購物需求'}).fill('買一隻無線滑鼠');
  const created=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/api/requests'));
  await page.getByRole('button',{name:'送出需求'}).click();
  const parent=await(await created).json();console.log('Created parent:',parent.request_id);
  await page.getByRole('heading',{name:'再確認一下',exact:true}).waitFor({timeout:65000});
  const parentState=await(await page.request.get(base+'/api/requests/'+parent.request_id)).json();
  console.log('Formatter:',JSON.stringify(parentState.formatter));
  assert.equal(parentState.formatter.provider,'openai');
  assert.ok(!parentState.formatter.questions.some(q=>q.field==='color'),'known preference must not be asked again');
  assert.deepEqual(new Set(parentState.formatter.questions.map(q=>q.field)),new Set(['budget','delivery']));
  await shot('02-questions');
  await page.getByRole('button',{name:'NT$1,000 以內',exact:true}).click();
  await page.getByRole('button',{name:'7 天內',exact:true}).click();
  await page.reload();
  await page.getByRole('heading',{name:'再確認一下',exact:true}).waitFor();
  assert.ok((await page.locator('textarea').evaluateAll(els=>els.map(e=>e.value))).includes('含運最高預算1000元'));
  await shot('03-answers');
  const continued=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/api/requests'));
  await page.getByRole('button',{name:'繼續',exact:true}).click();
  const child=await(await continued).json();console.log('Created child:',child.request_id);
  assert.equal(child.parent_request_id,parent.request_id);
  await page.getByRole('progressbar').waitFor();await shot('04-processing');
  await page.getByRole('heading',{name:'為你找到的優惠',exact:true}).waitFor({timeout:300000});
  const final=await(await page.request.get(base+'/api/requests/'+child.request_id)).json();
  console.log('Final:',JSON.stringify({request_id:final.request_id,status:final.status,formatter:final.formatter,intent:final.intent,offers:final.ranked_offers.length}));
  assert.equal(final.formatter.provider,'openai');assert.equal(final.intent.max_total_twd,1000);assert.equal(final.intent.delivery_days_max,7);
  assert.ok(final.intent.product_preferences.some(p=>p.attribute==='color'&&p.values.includes('black')));
  assert.equal(final.documents.preference_md,'偏好黑色');assert.equal(final.decision,null);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  assert.deepEqual(errors,[]);await shot('05-offers');console.log('PASS: real LLM Q&A, saved answers, preference inheritance, results; no purchase.');
} finally {await browser.close();}
