import { chromium } from '../frontend/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const base=process.env.OFFERMESH_E2E_URL??'http://127.0.0.1:5173';
const browser=await chromium.launch({headless:true,channel:process.env.OFFERMESH_BROWSER_CHANNEL??'msedge'});
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
const out=new URL('../frontend/test-results/runtime/',import.meta.url);mkdirSync(out,{recursive:true});
try {
  await page.goto(base+'/chat');
  await page.getByRole('button',{name:'開啟代理設定',exact:true}).click();
  await page.getByRole('button',{name:'儲存設定',exact:true}).click();
  await page.getByRole('button',{name:'AI 對話',exact:true}).click();
  await page.getByRole('textbox',{name:'輸入購物需求',exact:true}).fill('滑鼠800元左右，預算1000元含稅運，7天內到貨。');
  const response=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/api/requests'));
  await page.getByRole('button',{name:'送出需求',exact:true}).click();
  const initial=await (await response).json();assert.equal(initial.status,'formatting');
  await page.getByRole('button',{name:/查看.*組優惠/}).click({timeout:20000});
  await page.getByRole('heading',{name:'為你找到的優惠'}).waitFor();
  const result=await (await page.request.get(`${base}/api/requests/${initial.request_id}`)).json();
  assert.equal(result.status,'awaiting_user');assert.equal(result.seller_agents.length,5);
  assert.ok(result.ranked_offers.length>=5);assert.ok(result.seller_agents.some(s=>s.rounds.length>1));
  await page.screenshot({path:fileURLToPath(new URL('offers.png',out)),fullPage:true});
  await page.getByRole('button',{name:'立即採用',exact:true}).click();
  await page.getByText('決策已保存；尚未購買或付款。',{exact:true}).waitFor();
  await page.reload();await page.getByText('決策已保存；尚未購買或付款。',{exact:true}).waitFor();
  const saved=await (await page.request.get(`${base}/api/requests/${initial.request_id}`)).json();
  assert.equal(saved.status,'accepted');assert.equal(saved.selected_offer_id,result.ranked_offers[0].offer_id);
  await page.getByRole('button',{name:'開始新的購物需求',exact:true}).click();
  await page.getByRole('textbox',{name:'輸入購物需求',exact:true}).fill('買滑鼠，預算1000元，7天內到貨。');
  const nextResponse=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/api/requests'));
  await page.getByRole('button',{name:'送出需求',exact:true}).click();
  const next=await (await nextResponse).json();
  await page.getByRole('button',{name:/查看.*組優惠/}).click({timeout:20000});
  await page.getByRole('button',{name:'都不合適？補充需求',exact:true}).click();
  await page.getByRole('textbox',{name:'回饋內容',exact:true}).fill('  不要滑鼠墊，保留這段回饋。  ');
  await page.getByRole('button',{name:'送出回饋',exact:true}).click();
  await page.getByRole('heading',{name:'回饋已保存',exact:true}).waitFor();
  await page.reload();await page.getByRole('heading',{name:'回饋已保存',exact:true}).waitFor();
  const rejected=await (await page.request.get(`${base}/api/requests/${next.request_id}`)).json();
  assert.equal(rejected.status,'rejected');assert.equal(rejected.decision.feedback,'  不要滑鼠墊，保留這段回饋。  ');
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({passed:true,request_id:initial.request_id,sellers:result.seller_agents.length,offers:result.ranked_offers.length,flow:'UI -> formatter -> discovery -> negotiation -> evaluator -> accept/reject -> reload',url:page.url()}));
} finally {await browser.close();}
