import {useEffect,useRef,useState,type ReactNode} from 'react';
import {ArrowLeft,ArrowRight,Check,MessageCircle,ShieldCheck,Store} from 'lucide-react';
import {AppShell,ChatPanel,AgentDefinitionEditor,type ChatMessage,type ChatStatus,type DefinitionTab} from './components/chat';
import {OfferDeck,OfferDetails,NegotiationPanel,FeedbackForm} from './components/offers';
import {useWorkspace} from './state/useWorkspace';
import {currentRank,processing,type View} from './state/model';
import type {Offer,RequestSnapshot} from './contract.generated';
import './styles/chat.css';
import './styles/offers.css';
import {DecisionSummary} from './components/offers/DecisionSummary';

const stateCopy:Record<string,string>={formatting:'正在整理你的需求與購買限制。',orchestrating:'正在尋找符合需求的賣家。',negotiating:'各賣家正在獨立議價，完成後會一起比較。',evaluating:'正在根據預算、交期與偏好整理推薦。',needs_clarification:'需要更明確的需求才能繼續。',needs_confirmation:'有配件需要額外授權，尚未開放採用。',no_match:'目前沒有符合所有條件的方案。',failed:'這次比價未完成，請查看原因後重新開始。',accepted:'本輪已採用一個方案，決策已保存。',rejected:'你的回饋已保存。可開始新對話，繼續尋找合適的優惠。'};

export default function App(){
 const s=useWorkspace();const c=s.active;const snapshot=c.snapshot;const d=s.workspace.definitions;
 const [tab,setTab]=useState<DefinitionTab>('intent');
 const scrolls=useRef<Record<string,number>>({});const focusText=useRef('');const priorView=useRef<string>(s.view);
 const mainRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{const viewport=window.visualViewport;const resize=()=>document.documentElement.style.setProperty('--app-height',`${viewport?.height??window.innerHeight}px`);resize();viewport?.addEventListener('resize',resize);window.addEventListener('resize',resize);return()=>{viewport?.removeEventListener('resize',resize);window.removeEventListener('resize',resize);document.documentElement.style.removeProperty('--app-height');};},[]);
 const go=(view:View,id?:string|null,offerId?:string|null)=>{const el=mainRef.current?.querySelector('.workspace-content,.chat-thread');if(el)scrolls.current[s.view]=el.scrollTop;if(s.view==='offers')focusText.current=(document.activeElement?.textContent??'').trim();s.navigate(view,id,offerId);};
 useEffect(()=>{const focusScope=s.view+(snapshot&&['accepted','rejected'].includes(snapshot.status)?':'+snapshot.status:'');if(priorView.current===focusScope)return;priorView.current=focusScope;const frame=requestAnimationFrame(()=>{const root=mainRef.current;if(!root)return;let target:HTMLElement|null=null;if(s.view==='offers'&&focusText.current)target=Array.from(root.querySelectorAll<HTMLElement>('button')).find(b=>b.textContent?.trim()===focusText.current)??null;target??=root.querySelector<HTMLElement>('.chat-main-slot h1,.chat-main-slot h2,.chat-main-slot textarea');if(target){target.setAttribute('tabindex','-1');target.focus({preventScroll:true});}const sc=root.querySelector('.workspace-content,.chat-thread');if(sc)sc.scrollTop=scrolls.current[s.view]??0;});return()=>cancelAnimationFrame(frame);},[s.view,snapshot?.status]);
 const patch=(p:Parameters<typeof s.patch>[1])=>s.patch(c.id,p);
 const definitionEditor=<AgentDefinitionEditor intent={d.intent} preference={d.preference} savedIntent={d.savedIntent} savedPreference={d.savedPreference} activeTab={tab} onTabChange={setTab} onIntentChange={intent=>s.update(w=>({...w,definitions:{...w.definitions,intent}}))} onPreferenceChange={preference=>s.update(w=>({...w,definitions:{...w.definitions,preference}}))} onSave={s.saveDefinitions} onCancel={()=>s.update(w=>({...w,definitions:{...w.definitions,intent:w.definitions.savedIntent,preference:w.definitions.savedPreference}}))} saving={s.saving} error={s.error}/>;
 const ranking=currentRank(c);const offer=snapshot?.offers.find(o=>o.offer_id===ranking?.offer_id)??null;
 const pending=!!s.pending||s.busy||s.unknown;
 const expired=(o:Offer)=>Date.parse(o.expires_at)<=s.now||!!c.unavailableIds?.includes(o.offer_id);
 const verified=s.verified===c.requestId;
 const canFeedback=!!snapshot&&['awaiting_user','no_match','needs_confirmation'].includes(snapshot.status);
 const messages:ChatMessage[]=[];
 if(c.message)messages.push({id:'user-'+c.id,role:'user',content:c.message});
 if(c.historyMissing)messages.push({id:'missing-history',role:'system',content:'本分頁沒有原對話紀錄。以下顯示已發布的需求與結果。'});
 if(snapshot?.intent)messages.push({id:'intent-'+snapshot.request_id,role:'assistant',content:'我會依照以下條件，比較符合需求的優惠。',chips:['無線滑鼠','NT$'+snapshot.intent.max_total_twd.toLocaleString('zh-TW')+' 以內',snapshot.intent.delivery_days_max+' 天內送達']});
 if(snapshot){const text=snapshot.status==='awaiting_user'?`示範資料：${snapshot.seller_agents.length} 家虛擬賣家，找到 ${snapshot.ranked_offers.length} 組可選方案。`:stateCopy[snapshot.status]??'正在讀取本輪結果。';messages.push({id:'result-'+snapshot.request_id,role:'assistant',content:text+(snapshot.error?' '+snapshot.error.message:'')});}
 else if(s.pending?.kind==='create')messages.push({id:'sending',role:'assistant',content:s.unknown?'正在確認送出結果，請勿重複建立需求。':'收到需求，正在建立這次比價。'});
 const ready=snapshot?.status==='awaiting_user'&&verified&&snapshot.ranked_offers.some(r=>snapshot.offers.some(o=>o.offer_id===r.offer_id&&!expired(o)));
 const chatStatus:ChatStatus=s.pending?.kind==='create'?'sending':processing(snapshot?.status)?'processing':ready?'ready':snapshot&&snapshot.status!=='awaiting_user'?'failed':c.draft?'draft':'empty';
 const notice=s.error||s.unknown?<div className="global-notice" role="alert"><span>{s.unknown?'確認結果中。保留原提交，暫時鎖定操作。 ':''}{s.error}</span><button className="text-button" disabled={s.busy} onClick={s.retry}>{s.pending?'核對原提交':'重新載入'}</button></div>:null;
 const back=<button className="text-button" onClick={()=>go('chat')}><ArrowLeft size={17}/> 返回對話</button>;
 let content:ReactNode;
 if(s.view==='chat')content=<><ChatPanel messages={messages} status={chatStatus} teaser={ready?{requestId:snapshot.request_id,title:'查看優惠組合',offerCount:snapshot.ranked_offers.length,lowestTotalTwd:Math.min(...snapshot.ranked_offers.map(r=>snapshot.offers.find(o=>o.offer_id===r.offer_id)!.total_price_twd)),imageUrl:undefined}:undefined} draft={c.draft} onDraft={draft=>patch({draft})} onSend={s.send} onOpenOffers={id=>go('offers',id)} sending={pending||s.saving||processing(snapshot?.status)} error={s.error} unsavedDefinitions={d.intent!==d.savedIntent||d.preference!==d.savedPreference} savedDefinitionValid={!!d.savedIntent.trim()} onEditDefinitions={()=>go('settings')}/>{definitionEditor}{(pending||snapshot&&snapshot.status!=='awaiting_user'&&!processing(snapshot.status))&&<div className="chat-context-actions">{s.unknown&&<button className="button secondary" disabled={s.busy} onClick={s.retry}>核對原提交</button>}{snapshot&&<button className="text-button" onClick={()=>go('offers')}>查看本輪狀態 <ArrowRight size={16}/></button>}</div>}</>;
 else if(s.view==='settings')content=<div className="workspace-content editor-view content-enter">{back}{definitionEditor}</div>;
 else if(!snapshot)content=<div className="workspace-content">{back}{notice}<Status title={c.requestId?'正在載入這次比價':'還沒有購物需求'} text={c.requestId?'正在讀取已發布的結果，稍候即可繼續。':'先告訴 Buyer Agent 你的預算與用途。'} action={<button className="button primary" onClick={()=>go('chat')}>回到購物助理</button>}/></div>;
 else if(s.view==='history')content=<div className="workspace-content">{back}{notice}<button className="text-button" onClick={()=>go('offers')}>返回優惠</button><NegotiationPanel snapshot={snapshot} activeOfferId={offer?.offer_id} onSelectOffer={id=>go('details',undefined,id)}/></div>;
 else if(s.view==='details'){
   const detail=snapshot.offers.find(o=>o.offer_id===s.detailId);
   content=<div className="workspace-content">{notice}{detail?<OfferDetails snapshot={snapshot} offer={detail} ranking={snapshot.ranked_offers.find(r=>r.offer_id===detail.offer_id)??null} pending={pending||!verified} expired={expired(detail)} onBack={()=>go('offers')} onAccept={id=>s.accept(id)}/>:<Status title="找不到這個方案" text="此明細不屬於本輪結果。" action={<button className="button secondary" onClick={()=>go('offers')}>返回優惠</button>}/>}</div>;
 }else if(s.view==='feedback'&&canFeedback)content=<div className="workspace-content content-enter">{back}{notice}<FeedbackForm value={c.feedback} pending={pending||!verified} onChange={feedback=>patch({feedback})} onSubmit={s.reject} onCancel={s.review} fieldMessage={s.error} submitLabel="送出回饋"/>{c.skipped.length>0&&<button className="text-button new-round-link" disabled={pending} onClick={s.undo}>撤回最後一次略過</button>}</div>;
 else if(snapshot.status==='accepted'){
   const selected=snapshot.offers.find(o=>o.offer_id===snapshot.selected_offer_id);
   content=<div className="workspace-content content-enter">{back}{notice}{selected?<DecisionSummary snapshot={snapshot} offer={selected}/>:<Status title="方案資料不完整" text="無法確認被採用的方案，請重新載入。"/>}<button className="text-button new-round-link" onClick={s.newConversation}>開始新的購物需求</button></div>;
 }else if(snapshot.status==='rejected'&&snapshot.decision?.action==='reject')content=<div className="workspace-content content-enter">{back}{notice}<h1>回饋已保存</h1><p>Buyer Agent 尚未接入；此處不會改寫 intent 或建立下一輪。</p><h2>回饋內容</h2><pre>{snapshot.decision.feedback}</pre><h2>原始文件 · revision {snapshot.decision.source_documents.revision}</h2><h3>intent.md</h3><pre>{snapshot.decision.source_documents.intent_md}</pre><h3>preference.md</h3><pre>{snapshot.decision.source_documents.preference_md}</pre><details><summary>Buyer Agent 交接資料</summary><pre>{JSON.stringify(snapshot.decision,null,2)}</pre></details><button className="button secondary" onClick={s.newConversation}>新對話</button></div>;
 else if(snapshot.status!=='awaiting_user')content=<div className="workspace-content content-enter">{back}{notice}<Status title={processing(snapshot.status)?'Buyer Agent 正在比價':snapshot.status==='no_match'?'沒有符合條件的方案':'這次需求需要處理'} text={(stateCopy[snapshot.status]??'請回到對話查看進度。')+(snapshot.error?' '+snapshot.error.message:'')} action={canFeedback?<button className="button primary" onClick={()=>go('feedback')}>補充需求</button>:<button className="button secondary" onClick={s.newConversation}>新對話</button>}/>{snapshot.seller_agents.length>0&&<NegotiationPanel snapshot={snapshot}/>}</div>;
 else content=<div className="workspace-content content-enter" data-testid="offers-workspace">{notice}<div className="workspace-topline">{back}<div className="context-rail"><span><Store size={14}/> {snapshot.seller_agents.length} 家賣家 · {Math.max(0,...snapshot.seller_agents.map(seller=>seller.rounds.length))} 輪模擬議價</span><button className="text-button" onClick={()=>go('history')}>議價紀錄</button></div></div><h1 className="workspace-title">為你找到的優惠</h1><p className="workspace-subtitle">無線滑鼠 · 預算 NT${snapshot.intent?.max_total_twd.toLocaleString('zh-TW')} 內 · 獨立比較，依需求推薦</p><OfferDeck snapshot={snapshot} offer={offer} ranking={ranking??null} totalOffers={snapshot.ranked_offers.length} canUndo={c.skipped.length>0} pending={pending||!verified} expired={!!offer&&expired(offer)} disabledReason={s.unknown?'確認結果中':!verified?'正在核對方案':undefined} onAccept={id=>s.accept(id)} onSkip={s.skip} onUndo={s.undo} onDetails={id=>go('details',undefined,id)}/>{!offer&&<div className="status-panel"><h2>已瀏覽所有方案</h2><button className="button primary" onClick={()=>go('feedback')}>調整需求</button><button className="text-button" onClick={s.review}>重新瀏覽</button></div>}<div className="offers-footer"><button className="text-button" disabled={pending} onClick={()=>go('feedback')}>都不合適？補充需求</button><span className="app-demo"><ShieldCheck size={14}/> 示範優惠 · 無實際付款</span></div>{snapshot.sponsored_placement&&<Sponsored snapshot={snapshot}/>}</div>;
 return <div ref={mainRef} data-keyboard={s.source==='keyboard'}><AppShell activeView={s.view==='settings'?'definitions':s.view==='history'?'offers':s.view} recentRequests={s.workspace.conversations.map(item=>({id:item.id,title:item.title,isActive:item.id===c.id}))} onChat={()=>go('chat')} onSettings={()=>go('settings')} onNewConversation={s.newConversation} onSelectConversation={s.selectConversation}>{content}</AppShell></div>;
}
function Status({title,text,action}:{title:string;text:string;action?:ReactNode}){return <section className="status-panel"><span className="status-icon"><MessageCircle size={26}/></span><h2>{title}</h2><p>{text}</p><div className="actions">{action}</div><p className="app-demo">Demo · 使用可重現的虛擬市場，不會產生真實付款</p></section>;}
function Sponsored({snapshot}:{snapshot:RequestSnapshot}){const placement=snapshot.sponsored_placement!;const seller=snapshot.seller_agents.find(s=>s.seller_id===placement.seller_id);return <aside className="sponsored-placement" aria-label="Sponsored"><span>Sponsored</span><p>{seller?.name??'贊助商家'} <small>展示資訊，與推薦排名分開</small></p><Check size={14} aria-hidden="true"/></aside>;}
