import React from 'react';
import {createRoot} from 'react-dom/client';
import App from './App';
import './styles/global.css';
import './styles/workspace.css';
import './styles/mobile.css';
import './styles/blue.css';
import './styles/history.css';
import './styles/deal-progress.css';
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
